### ISSUE TITLE
Freeze after close an ads

### ISSUE THREAD

**Issue by hungly** [Drawnzer/File_Quest#20]
App freeze after return from an ads page.

# Step to re-create:
1. Click on the ads
2. Close the browser to back to program

# Result:
Freeze on tab “/” and “File gallery”

# Run in
* Samsung Galaxy Note 4
* Samsung's stock ROM 4.4.4

**Comment by Drawnzer** [comment]
its simply because of airpush sdk,no fault in my app.
I will remove airpush.
